name: OpenStreetMap

on:
  push:
    branches:
      - feature/osm

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          submodules: recursive

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ^1.21.0
      - run: go run ./downloader/03_osm.go ./downloader/osm

      - name: Setup Bun
        uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1
      - name: Build demo/parser CLI
        run: bun install && npm run bun:build
        working-directory: demo/parser
      - run: php transformers/osm/split.php | tee split.log

      - name: Prepare GitHub comment
        id: comment
        run: printf 'BODY<<EOF\n%s\nEOF\n' "$(cat split.log)" >> $GITHUB_OUTPUT
      - name: Post GitHub comment
        uses: daohoangson/comment-on-github@35b21121fdbadf807678bec8210cdd7f22a934fe # v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ github.sha }}

            ``` 
            ${{ steps.comment.outputs.BODY }}
            ```
          fingerprint: "### Statistics"
          replace: please
          
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          path: |
            data/osm.csv
            downloader/osm/working.json
