name: SonarCloud

on:
  push:

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node 18
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 18.x

      - name: firebase/functions
        run: |
          set -e
          npm ci
          npm run test:coverage
        working-directory: firebase/functions

      - name: Setup Node 20
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20.x

      - name: demo/parser
        run: |
          set -e
          npm ci
          npm run test:coverage
        working-directory: demo/parser

      - name: history
        run: |
          set -e
          npm ci
          npm run test:coverage
        working-directory: history

      - name: transformers/js-dvhcvn
        run: |
          set -e
          npm ci --ignore-scripts
          npm run test:coverage
        working-directory: transformers/js-dvhcvn

      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      - name: transformers/dart-dvhcvn
        run: |
          set -e
          dart pub get
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
        working-directory: transformers/dart-dvhcvn

      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
